### PR TITLE
Design page

### PR DESCRIPTION
**Pull request by antoinegourtay**

### CODE REVIEW

**Comment by armandfardeau** [comment]
@antoinegourtay Could you give us a little update on this?

**Comment by antoinegourtay** [comment]
Currently doing the second part of the screen

**Comment by armandfardeau** [comment]
@antoinegourtay Just have a look on the Header on mobile

image

Maybe a padding of 20px 20px 20px on mobile is better?

**Comment by antoinegourtay** [comment]
> @antoinegourtay Just have a look on the Header on mobile
> 
> image
> 
> Maybe a padding of 20px 20px 20px on mobile is better?

Fixed

**Comment by antoinegourtay** [comment]
l'image dans la fin de la 2ème partie du site est temporaire

**Pull request merged**
